### PR TITLE
Update compression algorithms in Caddyfile

### PR DESCRIPTION
**Pull request by gaby**
This update is based on Caddy official documentation:
- https://caddyserver.com/docs/caddyfile/directives/file_server
- https://caddyserver.com/docs/caddyfile/directives/encode

Related to https://github.com/static-web-server/static-web-server/pull/381

### CODE REVIEW

**Review by palant — COMMENTED** [review]
What do you intend with this change? We don’t have pre-compressed files other than gzip in the directory. And vegeta sends `Accept-Encoding: gzip` with its requests.

**Comment by gaby** [comment]
@palant So benchmarks are only run for gzip then? I was confused about, given they all support different compression algorithms.

Ex. NGINX doesn't have native zstd

**Comment by palant** [comment]
> @palant So benchmarks are only run for gzip then?

Yes, that’s what we have right now. In order to change that we would have to invest some effort: add pre-compressed files for other encodings, specify `Accept-Encoding` header for vegeta explicitly (three times the number of tests/results?), decide what to do about software not supporting particular encodings (nginx only supports gzip?), verify configurations across the board…

**Comment by gaby** [comment]
> > @palant So benchmarks are only run for gzip then?
> 
> Yes, that’s what we have right now. In order to change that we would have to invest some effort: add pre-compressed files for other encodings, specify `Accept-Encoding` header for vegeta explicitly (three times the number of tests/results?), decide what to do about software not supporting particular encodings (nginx only supports gzip?), verify configurations across the board…

Fair, will close. Can be revisited in the future.

**Pull request closed without merging**
